In [10]:
temperatures_w1 = np.array([22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9])

In [11]:
temperatures_w1

array([22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9])

In [12]:
print("Shape:", temperatures_w1.shape)
print("Data type:", temperatures_w1.dtype)
print("Number of elements:", temperatures_w1.size)

Shape: (7,)
Data type: float64
Number of elements: 7

In [13]:
fahrenheit = (temperatures_w1 * 9/5) + 32

print("Fahrenheit:", fahrenheit)
print("Maximum:", temperatures_w1.max())
print("Minimum:", temperatures_w1.min())
print("Mean:", temperatures_w1.mean())

Fahrenheit: [72.5  77.54 69.44 74.12 78.98 76.64 71.42]
Maximum: 26.1
Minimum: 20.8
Mean: 23.542857142857144

In [14]:
print("First 3 days:", temperatures_w1[:3])
print("Weekend:", temperatures_w1[-2:])
print("Middle 3 days:", temperatures_w1[2:5])

First 3 days: [22.5 25.3 20.8]
Weekend: [24.8 21.9]
Middle 3 days: [20.8 23.4 26.1]

In [15]:
temperatures = np.array([
    [22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9],
    [19.2, 22.5, 21.3, 24.0, 23.5, 22.8, 20.1]
])

temperatures

array([[22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9],
       [19.2, 22.5, 21.3, 24. , 23.5, 22.8, 20.1]])

In [16]:
print("Shape:", temperatures.shape)
print("Data type:", temperatures.dtype)
print("Number of elements:", temperatures.size)

Shape: (2, 7)
Data type: float64
Number of elements: 14

In [17]:
print("Week 1:", temperatures[0])
print("Week 2:", temperatures[1])

print("Week 1 weekend:", temperatures[0, -2:])
print("Week 2 weekend:", temperatures[1, -2:])

Week 1: [22.5 25.3 20.8 23.4 26.1 24.8 21.9]
Week 2: [19.2 22.5 21.3 24.  23.5 22.8 20.1]
Week 1 weekend: [24.8 21.9]
Week 2 weekend: [22.8 20.1]

In [18]:
import pandas as pd

marks = pd.Series(
    [95, 92, 89, 85, 80],
    index=["Rank1", "Rank2", "Rank3", "Rank4", "Rank5"]
)

marks

Rank1    95
Rank2    92
Rank3    89
Rank4    85
Rank5    80
dtype: int64

In [19]:
print("1st rank:", marks.iloc[0])

print("Top 3:")
print(marks.loc[["Rank1", "Rank2", "Rank3"]])

print("3rd rank:", marks.iloc[2])

print("Marks greater than 90:")
print(marks[marks > 90])

1st rank: 95
Top 3:
Rank1    95
Rank2    92
Rank3    89
dtype: int64
3rd rank: 89
Marks greater than 90:
Rank1    95
Rank2    92
dtype: int64

In [20]:
# Modify Rank1
marks.loc["Rank1"] = 100

# Remove Rank5
marks = marks.drop("Rank5")

# Calculate CGPA
cgpa = marks / 10

print("Updated marks:")
print(marks)

print("\nCGPA:")
print(cgpa)

Updated marks:
Rank1    100
Rank2     92
Rank3     89
Rank4     85
dtype: int64

CGPA:
Rank1    10.0
Rank2     9.2
Rank3     8.9
Rank4     8.5
dtype: float64

In [21]:
transactions = pd.DataFrame({
    'TransactionID': [101, 102, 103, 104, 105, 106, 107, 108, 109, 110],
    
    'ProductCategory': [
        'Electronics', 'Clothing', 'Electronics', 'Furniture',
        'Clothing', 'Electronics', 'Furniture', 'Clothing',
        'Furniture', 'Electronics'
    ],
    
    'Region': [
        'North', 'South', 'North', 'East', 'West',
        'North', 'East', 'West', 'South', 'North'
    ],
    
    'Amount': [200, 150, 300, 450, 200, 250, 300, 180, 350, 400]
})

print(transactions)

   TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     150
2            103     Electronics  North     300
3            104       Furniture   East     450
4            105        Clothing   West     200
5            106     Electronics  North     250
6            107       Furniture   East     300
7            108        Clothing   West     180
8            109       Furniture  South     350
9            110     Electronics  North     400

In [22]:
print("First 5 rows:")
print(transactions.head())

print("\nLast 5 rows:")
print(transactions.tail())

print("\nShape:", transactions.shape)

print("\nColumns:")
print(transactions.columns)

print("\nData types:")
print(transactions.dtypes)

First 5 rows:
   TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     150
2            103     Electronics  North     300
3            104       Furniture   East     450
4            105        Clothing   West     200

Last 5 rows:
   TransactionID ProductCategory Region  Amount
5            106     Electronics  North     250
6            107       Furniture   East     300
7            108        Clothing   West     180
8            109       Furniture  South     350
9            110     Electronics  North     400

Shape: (10, 4)

Columns:
Index(['TransactionID', 'ProductCategory', 'Region', 'Amount'], dtype='str')

Data types:
TransactionID      int64
ProductCategory      str
Region               str
Amount             int64
dtype: object

In [23]:
print("Product Category and Amount:")
print(transactions[["ProductCategory", "Amount"]])

Product Category and Amount:
  ProductCategory  Amount
0     Electronics     200
1        Clothing     150
2     Electronics     300
3       Furniture     450
4        Clothing     200
5     Electronics     250
6       Furniture     300
7        Clothing     180
8       Furniture     350
9     Electronics     400

In [24]:
print("Last 3 columns using iloc:")
print(transactions.iloc[:, -3:])

Last 3 columns using iloc:
  ProductCategory Region  Amount
0     Electronics  North     200
1        Clothing  South     150
2     Electronics  North     300
3       Furniture   East     450
4        Clothing   West     200
5     Electronics  North     250
6       Furniture   East     300
7        Clothing   West     180
8       Furniture  South     350
9     Electronics  North     400

In [25]:
filtered = transactions[
    (transactions["Region"] == "North") &
    (transactions["Amount"] > 200)
]

filtered

   TransactionID ProductCategory Region  Amount
2            103     Electronics  North     300
5            106     Electronics  North     250
9            110     Electronics  North     400

In [26]:
print(transactions["ProductCategory"].value_counts())

ProductCategory
Electronics    4
Clothing       3
Furniture      3
Name: count, dtype: int64

In [27]:
print(transactions["Region"].unique())

<StringArray>
['North', 'South', 'East', 'West']
Length: 4, dtype: str

In [28]:
transactions.groupby("Region")["Amount"].mean()

Region
East     375.0
North    287.5
South    250.0
West     190.0
Name: Amount, dtype: float64

In [29]:
transactions.loc[transactions["TransactionID"] == 102, "Amount"] = 165

transactions

   TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     165
2            103     Electronics  North     300
3            104       Furniture   East     450
4            105        Clothing   West     200
5            106     Electronics  North     250
6            107       Furniture   East     300
7            108        Clothing   West     180
8            109       Furniture  South     350
9            110     Electronics  North     400

In [30]:
transactions["Discount"] = transactions["Amount"] * 0.10

transactions

   TransactionID ProductCategory Region  Amount  Discount
0            101     Electronics  North     200      20.0
1            102        Clothing  South     165      16.5
2            103     Electronics  North     300      30.0
3            104       Furniture   East     450      45.0
4            105        Clothing   West     200      20.0
5            106     Electronics  North     250      25.0
6            107       Furniture   East     300      30.0
7            108        Clothing   West     180      18.0
8            109       Furniture  South     350      35.0
9            110     Electronics  North     400      40.0

In [31]:
transactions = transactions[
    transactions["TransactionID"] != 109
]

transactions

   TransactionID ProductCategory Region  Amount  Discount
0            101     Electronics  North     200      20.0
1            102        Clothing  South     165      16.5
2            103     Electronics  North     300      30.0
3            104       Furniture   East     450      45.0
4            105        Clothing   West     200      20.0
5            106     Electronics  North     250      25.0
6            107       Furniture   East     300      30.0
7            108        Clothing   West     180      18.0
9            110     Electronics  North     400      40.0

In [32]:
transactions = transactions.drop("Discount", axis=1)

transactions

   TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     165
2            103     Electronics  North     300
3            104       Furniture   East     450
4            105        Clothing   West     200
5            106     Electronics  North     250
6            107       Furniture   East     300
7            108        Clothing   West     180
9            110     Electronics  North     400